version: '3.8'

services:
  homeassistant:
    image: michaelhearn006/homeassistant:2.0.0
    hostname: homeassistant
    container_name: homeassistant
    restart: unless-stopped
    # Additional packages needed for DHCP and network tools
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BROADCAST
    environment:
      - TZ=Australia/Perth
    volumes:
      - /docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro  # For Bluetooth support
    
    networks:
      homeassistant_net:
        mac_address: "02:42:ac:11:00:02"
    
    # More robust init script with better error handling
    entrypoint: |
      sh -c "
        echo '=== Starting Home Assistant with DHCP Setup ==='
        
        # Function to log with timestamp
        log() {
          echo \"\$$(date '+%Y-%m-%d %H:%M:%S') - \$$1\"
        }
        
        # Wait for network interface to be ready
        log 'Waiting for network interface...'
        sleep 5
        
        # Get the interface name (more robust detection)
        IFACE=\$$(ip route | grep '^default' | awk '{print \$$5}' | head -1)
        if [ -z \"\$$IFACE\" ]; then
          IFACE=\$$(ip link | grep -E '^[0-9]+: eth[0-9]+' | head -1 | cut -d: -f2 | tr -d ' ')
        fi
        
        log \"Network interface detected: \$$IFACE\"
        
        if [ -n \"\$$IFACE\" ]; then
          # Install DHCP client if not present
          if ! command -v dhclient >/dev/null 2>&1 && ! command -v udhcpc >/dev/null 2>&1; then
            log 'Installing DHCP client...'
            if command -v apk >/dev/null 2>&1; then
              apk add --no-cache dhclient
            elif command -v apt-get >/dev/null 2>&1; then
              apt-get update && apt-get install -y isc-dhcp-client
            fi
          fi
          
          # Try DHCP with hostname (better for UDM Pro identification)
          if command -v dhclient >/dev/null 2>&1; then
            log 'Requesting DHCP lease with dhclient...'
            echo \"send host-name \\\"homeassistant\\\";\" > /etc/dhcp/dhclient.conf
            dhclient -v \$$IFACE
          elif command -v udhcpc >/dev/null 2>&1; then
            log 'Requesting DHCP lease with udhcpc...'
            udhcpc -i \$$IFACE -f -q -x hostname:homeassistant &
          else
            log 'Warning: No DHCP client available, relying on automatic assignment'
          fi
          
          # Wait a bit for DHCP to complete
          sleep 3
          
          # Display network information
          IP=\$$(ip addr show \$$IFACE | grep 'inet ' | awk '{print \$$2}' | cut -d/ -f1)
          if [ -n \"\$$IP\" ]; then
            log \"DHCP successful - IP assigned: \$$IP\"
            log \"MAC Address: \$$(cat /sys/class/net/\$$IFACE/address)\"
          else
            log 'Warning: No IP address detected'
          fi
        else
          log 'Error: Could not detect network interface'
        fi
        
        log 'Starting Home Assistant...'
        exec /init
      "
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"] 
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

networks:
  homeassistant_net:
    driver: macvlan
    driver_opts:
      parent: enxc8a362d09bc7  # Verify this is your correct interface
      macvlan_mode: bridge
    enable_ipv6: false  # Disable IPv6 if not needed