version: '3.3'

services:
  homeassistant:
    # Option 1: Use pre-built image (recommended)
    image: michaelhearn006/homeassistant:1.5.0

    # Option 2: Build from local Dockerfile (uncomment if needed)
    # build:
    #   context: .
    #   dockerfile: Dockerfile

    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=Australia/Perth  # Change to your timezone
    volumes:
      # Main config directory - this maps host /docker/homeassistant to container /config
      - /docker/homeassistant:/config
      # Local time for proper timestamps
      - /etc/localtime:/etc/localtime:ro
      # Optional: USB device access (uncomment if needed for Zigbee/Z-Wave)
      # - /dev/ttyUSB0:/dev/ttyUSB0
      # - /dev/ttyACM0:/dev/ttyACM0
    
    ports:
      - "8123:8123"
    
    # Use host network for device discovery (recommended for HA)
    network_mode: host
    
    # Optional: Add privileged mode if you need access to hardware
    # privileged: true
    
    # Optional: Add device access
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyACM0:/dev/ttyACM0
    
    # Optional: Add capabilities
    # cap_add:
    #   - NET_ADMIN
    #   - NET_RAW
    
    # Health check override (optional)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Optional: Define custom network if not using host mode
# networks:
#   homeassistant:
#     driver: bridge
